version: "3.6"

services:
  flask-app:
    container_name: Flask-Application
    build: .
    command: python run.py
    ports:
      - "5000":"5000"
    volumes:
      - flask-data:/flask-app
    links:
      - mongo-db
    depends_on:
      - mongo-db
  mongo-db:
    container_name: Mongo-Application
    image: mongo:latest
    hostname: mongo_db_application
    environment:
     - MONGO_INITDB_DATABASE=FountainHead
    volumes:
      - mongo-data:/data/db
