pipeline{
  agent any
  stages{
    stage("first-test")
    {
      steps{
      echo "Current workspace is $WORKSPACE"
      script {
        def path = "$WORKSPACE"
      }
      }
    }
    stage("deploy"){
        steps{
            sshagent(['docker-machine']) {
                // some block
                sh """
                ssh -o StrictHostKeyChecking=no $path dmonish3@34.72.181.130:/home/dmonish3/apps
                echo "now in remote vm"
                echo $path
                """
            }
        }
    }
  }
}
