pipeline{
  agent any
  stages{
    stage("first-test")
    {
      steps{
        script {
            env.PATH = "$WORKSPACE"
        }
        echo "${env.PATH }"
      }
    }
    stage("deploy"){
        steps{
            sshagent(['docker-aws']) {
                // some block
                sh "scp -o StrictHostKeyChecking=no ${env.PATH } ubuntu@3.134.115.63:/home/ubuntu"
                echo "test"
            }
        }
    }
  }
}
