pipeline{
  agent any
  stages{
    stage("first-test")
    {
      steps{
      script {
        def path = "$WORKSPACE"
      }
        echo "Current workspace is $path"
      }
    }
    stage("deploy"){
        steps{
            sshagent(['docker-machine']) {
                // some block
                sh """
               
                echo "now in remote vm"
                echo $path
                """
            }
        }
    }
  }
}
