app:
   build: .
   container_name: flask-application
   ports:
     - 5000:5000
   volumes:
     - .:/flask-app
   links:
     - db
db:
   image: mongo:latest
   container_name: mongo_database
   hostname: mongo_db_application
   environment:
     - MONGO_INITDB_DATABASE=FountainHead
   volumes:
     - ./mongo_data:/data/db
   ports:
     - 27017:27017
